version: '3'
services:
  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
    networks:
      - todonet01 


  todoback:
    image: todobackend
    ports:
      - 3001:3001
    networks:
      - todonet01 


  todotests:
    image: todotests
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback
    networks:
      - todonet01


networks:
    todonet01: